#!/bin/sh
#
# This script is used by busybox
#
# Copyright (C) 2025 Charleye <wangkart@aliyun.com>
#


start() {
	echo "Running abc to mark AB metadata ..."

	return 0
}

case "$1" in
	start)
		start ;;
	stop)
		:;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
esac
